<?xml version='1.0'?>

<robot name="bot" 
  xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:property name="robotname" value="bot"/>
  <xacro:property name="set_gazebo_plugins" value="1"/>

  <xacro:macro name="default_origin">
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </xacro:macro>

<!-- BASE_LINK PARAMETERS -->
  <xacro:property name="bot_mass" value="30.0"/>
  <xacro:property name="bot_width" value="0.75"/>
  <xacro:property name="bot_height" value="0.5"/>
  <xacro:property name="distance_between_wheels" value="0.6"/>
  <xacro:property name="wheel_diameter" value="0.1" />
  <xacro:property name="below_offset_btwn_base_wheel" value="0.02"/>
  <xacro:property name="wheel_thickness" value="0.02"/>

  <xacro:macro name="base_geometry">
    <geometry>
      <box size="${bot_width} ${bot_width} ${bot_height}"/>
    </geometry>
  </xacro:macro>
  
  <xacro:macro name="default_inertia">
    <inertia ixx="0.6" ixy="0" ixz="0" iyy="0.65" iyz="0" izz="0.21"/>
  </xacro:macro>


<!-- WHEEL PARAMETERS -->
  <xacro:macro name="wheel_inertia">
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
  </xacro:macro>

  <xacro:macro name="wheel_geometry_common">
      <geometry>
          <cylinder radius="${wheel_diameter/2}" length="${wheel_thickness}"/>
      </geometry>
  </xacro:macro>

  <xacro:macro name="wheel_orientation_x">
    <origin xyz="0 0 0" rpy="0 ${pi/2} ${pi/2}"/>
  </xacro:macro>

  <xacro:macro name="wheel_orientation_y">
    <origin xyz="0 0 0" rpy="0 ${pi/2} 0"/>
  </xacro:macro>

  <xacro:macro name="joint_axis_x">
    <axis xyz="0 1 0" rpy="0 0 0" />
  </xacro:macro>
  <xacro:macro name="joint_axis_y">
    <axis xyz="1 0 0" rpy="0 0 0" />
  </xacro:macro>
  <!-- origin_wheel - location of where the wheel is attached
        wheel_orientation - the direction (axis) of where the wheel is turned straight to
        joint_orientation - the axis in which direction the joint rotates the wheel straight to
        e.g. - wheel's axis is y - so it rotates in the way so robot goes straight in x axis.
        so wheel_orientation is x, joint_orientation is x 
        joint_origin - the location of where the slider joint is attached (should be at the very edge of the bottom
        of the base_link-->
  <xacro:macro name="wheel" params="name *wheel_orientation *joint_orientation *joint_origin">
    <joint name="${name}_base_joint" type="prismatic">
      <parent link="base_link"/>
      <child link="${name}_base_joint"/>
      <limit effort="1000.0" lower="${-below_offset_btwn_base_wheel}" upper="${wheel_diameter}" velocity="0.2"/>
      <xacro:insert_block name="joint_origin"/>
      <axis xyz="0 0 1" rpy="0 0 0" />
    </joint>

    <joint name="${name}_wheel_joint" type="continuous">
      <xacro:insert_block name="joint_orientation"/>
      <parent link="${name}_base_joint"/>
      <child link="${name}_wheel"/>
      <!--xacro:insert_block name="origin_wheel"/-->
      <!-- commented because origin of the wheels should be aligned with origin of the sliders -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="${name}_wheel">
      <visual>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
        <xacro:wheel_geometry_common/>
        <xacro:insert_block name="wheel_orientation"/>
      </visual>
      <collision>
        <xacro:wheel_geometry_common/>
        <xacro:insert_block name="wheel_orientation"/>
      </collision>
      <inertial>
        <xacro:wheel_geometry_common/>
        <xacro:insert_block name="wheel_orientation"/>
        <mass value="${wheel_mass}"/>
        <xacro:wheel_inertia/>
      </inertial>
    </link>
      <!-- GAZEBO settings for wheels -->
    <gazebo reference="${name}_wheel">
      <mu1>1000000.0</mu1>
      <mu2>1000000.0</mu2>
      <minDepth>0.0001 </minDepth>
      <fdir1 value = "1 0 0"/>
      <kp>100000.0</kp>
      <kd>100000 </kd>
      <material>Gazebo/Black</material>
    </gazebo>
  </xacro:macro>


<!-- DEFINITIONS OF ROBOT -->
  <!-- BASE LINK -->
  <link name='base_link'>
    <pose>0 0 0 0 0 0</pose>

    <inertial>
      <mass value="${bot_mass}"/>
      <xacro:default_inertia/>
    </inertial>

    <collision name='collision'>
      <xacro:default_origin/>
      <xacro:base_geometry/>
    </collision>

    <visual name='visual'>
       <xacro:default_origin/>
       <xacro:base_geometry/>
    </visual>
  </link>

  <!-- WHEELS -->
  
  <xacro:wheel name="1y">
    <xacro:insert_block name="wheel_orientation_y"/>
    <xacro:insert_block name="joint_axis_y"/>
    <origin xyz="${bot_width/2} ${-distance_between_wheels/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>

  <xacro:wheel name="2y">
    <xacro:insert_block name="wheel_orientation_y"/>
    <xacro:insert_block name="joint_axis_y"/>
    <origin xyz="${bot_width/2} ${distance_between_wheels/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="3y">
    <xacro:insert_block name="wheel_orientation_y"/>
    <xacro:insert_block name="joint_axis_y"/>
    <origin xyz="${-bot_width/2} ${-distance_between_wheels/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="4y">
    <xacro:insert_block name="wheel_orientation_y"/>
    <xacro:insert_block name="joint_axis_y"/>
    <origin xyz="${-bot_width/2} ${distance_between_wheels/2} ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="5x">
    <xacro:insert_block name="wheel_orientation_x"/>
    <xacro:insert_block name="joint_axis_x"/>
    <origin xyz="${distance_between_wheels/2} ${bot_width/2 } ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="6x">
    <xacro:insert_block name="wheel_orientation_x"/>
    <xacro:insert_block name="joint_axis_x"/>
    <origin xyz="${-distance_between_wheels/2} ${bot_width/2 } ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="7x">
    <xacro:insert_block name="wheel_orientation_x"/>
    <xacro:insert_block name="joint_axis_x"/>
    <origin xyz="${distance_between_wheels/2} ${-bot_width/2 } ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>
  <xacro:wheel name="8x">
    <xacro:insert_block name="wheel_orientation_x"/>
    <xacro:insert_block name="joint_axis_x"/>
    <origin xyz="${-distance_between_wheels/2} ${-bot_width/2 } ${-bot_height/2}" rpy="0 0 0"/>
  </xacro:wheel>

  <!-- LIDAR -->

  <joint name="lidar_joint" type="fixed">
    <axis xyz="0 0 0" />
    <origin xyz="${bot_length*6/7} 0 ${bot_height}" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="lidar"/>
  </joint>

  <link name="lidar">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.03"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.03"/>      
      </geometry>
    </visual>
    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>
  <!-- GAZEBO PLUGINS -->
  <gazebo>
    <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
      <alwaysOn>true</alwaysOn>
      <publishTf>1</publishTf>
      <updateRate>50</updateRate>
      <leftJoint>left_wheel_joint</leftJoint>
      <rightJoint>right_wheel_joint</rightJoint>
      <wheelSeparation>0.2</wheelSeparation>
      <wheelDiameter>0.05</wheelDiameter>
      <torque>75</torque>
      <commandTopic>cmd_vel</commandTopic>
      <odometryTopic>odom</odometryTopic>
      <odometryFrame>odom</odometryFrame>
      <robotBaseFrame>base_link</robotBaseFrame>
      <odometrySource>world</odometrySource>
      <publishWheelTF>true</publishWheelTF>
      <publishWheelJointState>true</publishWheelJointState>
    </plugin>
  </gazebo>

  <gazebo reference="ball">
    <kp>1000000.0</kp>
    <kd>10000</kd>
    <dampingFactor>0.0</dampingFactor>
    <mu1>0.00</mu1>
    <mu2>0.00</mu2>
    <fdir1 value = "1 0 0"/>
    <maxVel>15.0</maxVel>
    <material>Gazebo/Red</material>
  </gazebo> 

  <gazebo reference="lidar">
    <sensor type="ray" name="head_hokuyo_sensor_front">
      <pose>0 0 0 0 0 0</pose>
      <visualize>true</visualize>
      <update_rate>40</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>720</samples>
            <resolution>1</resolution>
            <min_angle>-1.3</min_angle>
            <max_angle>1.3</max_angle>
            <!-- 1.570796 -->
          </horizontal>
        </scan>
        <range>
          <min>0.1</min>
          <max>30.0</max>
          <resolution>0.01</resolution>
        </range>
        <noise>
          <type>gaussian</type>
          <!-- Noise parameters based on published spec for Hokuyo laser
               achieving "+-30mm" accuracy at range < 10m.  A mean of 0.0m and
               stddev of 0.01m will put 99.7% of samples within 0.03m of the true
               reading. -->
          <mean>0.0</mean>
          <stddev>0.01</stddev>
        </noise>
      </ray>
      <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_laser.so">
        <topicName>scan</topicName>
        <frameName>lidar</frameName>
      </plugin>
    </sensor>
  </gazebo>
</robot>